(() => {
  'use strict';
  const esc=(value='')=>String(value).replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));

  function markup(data){
    const careers=data?.careers||[];
    const first=careers[0]||{};
    const steps=[['role','Choose your desk'],['sequence','Learn in the right order'],['work','Practice real work'],['change','Handle new information'],['proof','Prove readiness']];
    return `<section class="cm-learner-guide-hero"><div class="container"><div><div class="eyebrow">INTERACTIVE LEARNER GUIDE · 5 MINUTE TOUR</div><h1>See exactly how you go from beginner to desk-ready.</h1><p>Choose a finance role, see the learning sequence, try a real model check, respond to changing information, and understand what your evidence proves.</p><div class="hero-actions"><a class="btn btn-gold" href="#/careers">Choose a Career →</a><a class="btn btn-outline cm-guide-hero-outline" href="#/employers">I represent a firm</a></div></div><div class="cm-guide-route-map" aria-label="Learner journey"><span>LEARN</span><i>→</i><span>SEE</span><i>→</i><span>PRACTICE</span><i>→</i><span>SIMULATE</span><i>→</i><span>PROVE</span></div></div></section>
    <section class="section cm-learner-guide"><div class="container"><div class="cm-learner-guide-shell"><nav class="card cm-learner-guide-nav" aria-label="Learner guide steps">${steps.map((step,index)=>`<button type="button" class="${index===0?'active':''}" data-learner-guide-tab="${step[0]}" aria-selected="${index===0?'true':'false'}"><span>${String(index+1).padStart(2,'0')}</span><div><b>${step[1]}</b><small>${index===0?'Start here':'Open step'}</small></div></button>`).join('')}<div class="cm-learner-guide-meter"><span data-learner-guide-progress>Step 1 of 5</span><i><b style="width:20%"></b></i></div></nav><div class="cm-learner-guide-panels">
      <article class="card cm-learner-guide-panel active" data-learner-guide-panel="role"><div class="eyebrow">STEP 1 · ROLE BEFORE THEORY</div><h2>Start with the job you want to understand.</h2><p>You do not need to know finance first. Capital Mastery shows the role, its purpose, the work products, and the decisions before asking you to learn technical language.</p><label class="cm-guide-career-picker">Preview a career<select data-guide-career>${careers.map((career,index)=>`<option value="${esc(career.id)}" ${index===0?'selected':''}>${esc(career.title)} — ${esc(career.role)}</option>`).join('')}</select></label><div class="cm-guide-role-card" data-guide-role-card><span>${esc(first.group||'Finance')}</span><h3>${esc(first.role||'Entry-level finance role')}</h3><p>${esc(first.description||'Choose a role to preview its work.')}</p><div><b>Typical work</b><small>${esc((first.deliverables||[]).slice(0,3).join(' · '))}</small></div></div><div class="cm-guide-standard"><strong>Why this matters</strong><p>Learning becomes easier when every concept has a visible job purpose. You always know what the skill is for and where it returns later.</p></div></article>
      <article class="card cm-learner-guide-panel" data-learner-guide-panel="sequence"><div class="eyebrow">STEP 2 · LEARN BEFORE YOU ARE GRADED</div><h2>Every new skill follows the same transfer sequence.</h2><div class="cm-guide-learning-loop">${[['Teach','Plain-language concept, purpose, inputs, units and common mistakes.'],['Demonstrate','A worked professional example with source and formula trace.'],['Guided practice','Prompts, checks and review standards while you build.'],['Independent work','Produce the work without step-by-step prompts.'],['Feedback + revision','Fix the work and explain what changed before the official gate.']].map((item,index)=>`<div><span>${index+1}</span><b>${item[0]}</b><small>${item[1]}</small></div>`).join('')}</div><div class="cm-guide-standard"><strong>No surprise assessment rule</strong><p>If an assessment, Applied Work assignment or Role Lab expects a skill, the pathway must teach it and let you practice it first.</p></div></article>
      <article class="card cm-learner-guide-panel" data-learner-guide-panel="work"><div class="eyebrow">STEP 3 · TRY THE WORKBENCH</div><h2>A model is more than a decorated form.</h2><p>Change the blue input cells. The formula cell recalculates, the formula bar explains the logic, and the reviewer check connects the number to a decision.</p><div class="cm-guide-workbook"><div class="cm-guide-workbook-title"><b>Training Model · Operating Snapshot</b><span>CALCULATION: AUTOMATIC</span></div><div class="cm-guide-workbook-ribbon"><span>File</span><span class="active">Home</span><span>Formulas</span><span>Data</span><span>Review</span></div><div class="cm-guide-workbook-formula"><b>C4</b><span>fx</span><code>= EBITDA / Revenue</code></div><table><thead><tr><th></th><th>A</th><th>B</th><th>C</th></tr></thead><tbody><tr><th>1</th><td>Metric</td><td>Value</td><td>Source / formula</td></tr><tr><th>2</th><td>Revenue ($m)</td><td class="input"><input data-guide-revenue type="number" min="0" step="any" value="250" aria-label="Revenue in millions"></td><td>Case file</td></tr><tr><th>3</th><td>EBITDA ($m)</td><td class="input"><input data-guide-ebitda type="number" step="any" value="50" aria-label="EBITDA in millions"></td><td>Case file</td></tr><tr><th>4</th><td>EBITDA margin</td><td class="formula" data-guide-margin>20.0%</td><td>= B3 / B2</td></tr></tbody></table><div class="cm-guide-workbook-tabs"><span class="active">Operating Case</span><span>Checks</span><span>Manager Note</span></div></div><div class="cm-guide-model-check" role="status" aria-live="polite" data-guide-model-check><b>Reviewer check</b><span>A 20.0% margin means $0.20 of EBITDA for each $1.00 of revenue. Next, compare it with the prior period or downside case before making a recommendation.</span></div></article>
      <article class="card cm-learner-guide-panel" data-learner-guide-panel="change"><div class="eyebrow">STEP 4 · REAL WORK CHANGES MIDSTREAM</div><h2>The case does not wait politely for you to finish.</h2><p>Role Labs introduce a material update only when the update genuinely changes the work. You must trace it through assumptions, outputs, risks and the recommendation.</p><div class="cm-guide-case-update"><div><span>ORIGINAL CASE</span><b>Revenue $250m · EBITDA $50m</b><small>Margin 20.0% · base recommendation under review</small></div><button type="button" class="btn btn-primary" data-guide-apply-update>Receive case update →</button><div class="cm-guide-update-result" data-guide-update-result hidden><span>NEW INFORMATION RECEIVED</span><b>A customer representing $20m of revenue requests a 10% pricing concession.</b><ol><li>Revise revenue and profit assumptions.</li><li>State the margin and valuation/credit impact.</li><li>Identify the control or diligence action.</li><li>Update the recommendation and next step.</li></ol></div></div><div class="cm-guide-standard"><strong>What is graded</strong><p>Not whether you clicked the update. The evidence is whether you changed the affected work correctly and communicated the consequence.</p></div></article>
      <article class="card cm-learner-guide-panel" data-learner-guide-panel="proof"><div class="eyebrow">STEP 5 · EVIDENCE, NOT JUST COMPLETION</div><h2>Your result shows what you can do.</h2><div class="cm-guide-proof-stack">${[['Knowledge','Official assessed understanding','Secure questions and calculations at the 80% standard.'],['Work product','Models, analyses, memos and decisions','Role-format evidence with source, logic, risk and communication checks.'],['Revision','Response to manager feedback','Attempt history shows whether you can improve the work.'],['Role Lab','Integrated job simulation','A changing synthetic case completed in the sequence the job requires.'],['Credential','Verified final evidence','Issued only when every required gate is met.']].map((item)=>`<div><span>${item[0]}</span><b>${item[1]}</b><small>${item[2]}</small></div>`).join('')}</div><div class="cm-guide-finish"><div><strong>Ready to start?</strong><p>Pick one career and complete Part 1. You can change pathways at any time.</p></div><a class="btn btn-gold" href="#/careers">Explore all 16 Careers →</a></div></article>
    </div></div></div></section>`;
  }

  function bind(data){
    const tabs=[...document.querySelectorAll('[data-learner-guide-tab]')],panels=[...document.querySelectorAll('[data-learner-guide-panel]')];
    const progress=document.querySelector('[data-learner-guide-progress]'),meter=document.querySelector('.cm-learner-guide-meter i b');
    tabs.forEach((button,index)=>button.addEventListener('click',()=>{const id=button.dataset.learnerGuideTab;tabs.forEach((item)=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active));});panels.forEach((panel)=>panel.classList.toggle('active',panel.dataset.learnerGuidePanel===id));if(progress)progress.textContent=`Step ${index+1} of ${tabs.length}`;if(meter)meter.style.width=`${Math.round((index+1)/tabs.length*100)}%`;}));
    const picker=document.querySelector('[data-guide-career]'),roleCard=document.querySelector('[data-guide-role-card]');
    picker?.addEventListener('change',()=>{const career=(data?.careers||[]).find((item)=>item.id===picker.value);if(!career||!roleCard)return;roleCard.innerHTML=`<span>${esc(career.group)}</span><h3>${esc(career.role)}</h3><p>${esc(career.description)}</p><div><b>Typical work</b><small>${esc((career.deliverables||[]).slice(0,3).join(' · '))}</small></div>`;});
    const revenue=document.querySelector('[data-guide-revenue]'),ebitda=document.querySelector('[data-guide-ebitda]'),margin=document.querySelector('[data-guide-margin]'),check=document.querySelector('[data-guide-model-check] span');
    const calculate=()=>{const r=Number(revenue?.value||0),e=Number(ebitda?.value||0),value=r>0?e/r*100:0;if(margin)margin.textContent=`${value.toFixed(1)}%`;if(check)check.textContent=r>0?`A ${value.toFixed(1)}% margin means $${(value/100).toFixed(2)} of EBITDA for each $1.00 of revenue. Next, compare it with the prior period or downside case before making a recommendation.`:'Revenue must be greater than zero before the margin formula can calculate.';};
    revenue?.addEventListener('input',calculate);ebitda?.addEventListener('input',calculate);
    document.querySelector('[data-guide-apply-update]')?.addEventListener('click',(event)=>{const result=document.querySelector('[data-guide-update-result]');if(!result)return;result.hidden=false;event.currentTarget.textContent='Case update received ✓';event.currentTarget.disabled=true;});
  }
  window.CM_LEARNER_GUIDE={markup,bind};
})();

