import fs from 'node:fs';import vm from 'node:vm';
const data=fs.readFileSync(new URL('../data.js',import.meta.url),'utf8');const appCode=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
class Store{m=new Map();getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}}
const appEl={innerHTML:''};const dummy=()=>({innerHTML:'',hidden:false,className:'',style:{},value:'',dataset:{},disabled:false,appendChild(){},remove(){},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},select(){},click(){},getContext(){return {fillRect(){},strokeRect(){},fillText(){},measureText(){return{width:10}},drawImage(){},scale(){}}},toDataURL(){return'data:'}});let handler=()=>{};const document={title:'',body:{appendChild(){}},getElementById(id){return id==='app'?appEl:dummy()},querySelector(){return dummy()},querySelectorAll(){return[]},createElement(){return dummy()},execCommand(){return true}};const location={hash:'',origin:'http://x',pathname:'/'};const localStorage=new Store(),sessionStorage=new Store();const windowObj={addEventListener(t,f){if(t==='hashchange')handler=f},scrollTo(){},open(){},print(){}};const ctx={window:windowObj,document,location,localStorage,sessionStorage,navigator:{clipboard:{writeText:async()=>{}}},console,Intl,Date,Math,URLSearchParams,URL:{createObjectURL(){return''},revokeObjectURL(){}},Blob:class{},Image:class{},XMLSerializer:class{serializeToString(){return''}},confirm(){return true},setTimeout(){}};Object.assign(windowObj,ctx);vm.createContext(ctx);vm.runInContext(data,ctx);vm.runInContext(appCode,ctx);
windowObj.CM_AUTH={ready:true,backendVerified:true,isAdmin:true,user:{uid:'logic-admin'}};
function state(){return JSON.parse(localStorage.getItem('capitalMasteryQaStateV2'))}
localStorage.setItem('capitalMasteryQaPreviewV1','true');
windowObj.CM.qaScores(79);let s=state();if((s.credentials||[]).length!==0)throw new Error('79% must not issue credentials');
windowObj.CM.qaScores(80);s=state();if((s.credentials||[]).length!==3)throw new Error('80% all-gates QA state should issue 3 preview credentials');
windowObj.CM.resetState();windowObj.CM.qaProgress(40);s=state();const ib=s.careers['investment-banking'];if(!ib.completedParts.includes(2)||ib.completedParts.includes(3))throw new Error('40% progress state incorrect');if((s.credentials||[]).length!==1||s.credentials[0].type!=='foundations')throw new Error('40% state should issue only Foundations preview credential');
windowObj.CM.qaProgress(80);s=state();if((s.credentials||[]).filter(x=>x.careerId==='investment-banking').length!==2)throw new Error('80% state should issue Foundations + Applied only');
if(localStorage.getItem('capitalMasteryLocalStateV1')!==null)throw new Error('QA controls contaminated normal learner state');
console.log('LOGIC AUDIT PASS: 79/80 boundary, 40/80 progress, credential gating, and QA isolation verified.');
