INSERT OR REPLACE INTO diagnostic_questions
(id,pathway_id,version,competency_id,position,prompt,options_json,correct_answer,rationale,status) VALUES
('ibd1','investment-banking','2.0','cmp_ib_accounting',1,'A company reports revenue of $500m and EBITDA of $75m. What is its EBITDA margin?','["10%","12%","15%","18%"]','15%','EBITDA margin equals EBITDA divided by revenue.','active'),
('ibd2','investment-banking','2.0','cmp_ib_ev',2,'A company has $900m equity value, $160m debt and $40m cash. What is enterprise value?','["$700m","$780m","$1,020m","$1,100m"]','$1,020m','Enterprise value equals equity value plus debt less cash.','active'),
('ibd3','investment-banking','2.0','cmp_ib_comps',3,'Why might an analyst exclude a peer from a trading-comps set?','["Its stock price increased yesterday","Its business model and growth profile are not meaningfully comparable","It has a different company name","It publishes quarterly earnings"]','Its business model and growth profile are not meaningfully comparable','Peer selection should reflect operating, growth, risk and economic comparability.','active'),
('ibd4','investment-banking','2.0','cmp_ib_dcf',4,'Holding everything else constant, what generally happens to a DCF valuation when WACC increases?','["Valuation increases","Valuation decreases","Valuation never changes","Only revenue changes"]','Valuation decreases','A higher discount rate reduces the present value of future cash flows.','active'),
('ibd5','investment-banking','2.0','cmp_ib_precedents',5,'Compared with trading comps, precedent-transaction multiples often include what additional effect?','["Control premium","Inventory write-off","Payroll tax","Dividend yield only"]','Control premium','Acquisition prices often reflect a premium for control.','active'),
('ibd6','investment-banking','2.0','cmp_ib_ma',6,'In a simplified acquisition, which item belongs in Sources rather than Uses?','["Purchase of target equity","Refinancing target debt","New acquisition debt","Transaction fees"]','New acquisition debt','Sources describe how the transaction is funded; uses describe where the funds go.','active'),
('ibd7','investment-banking','2.0','cmp_ib_review',7,'A valuation model shows enterprise value below equity value even though the company has positive net debt. What should you do first?','["Assume it is correct","Check the EV-to-equity bridge and debt/cash signs","Increase terminal growth","Delete the debt line"]','Check the EV-to-equity bridge and debt/cash signs','Positive net debt should normally make enterprise value exceed equity value, so the bridge deserves review.','active'),
('ibd8','investment-banking','2.0','cmp_ib_judgment',8,'A target looks attractive on headline growth but customer concentration is extreme. What is the strongest analyst response?','["Ignore concentration because growth is high","Flag concentration as a diligence and downside risk and test its effect","Automatically reject every concentrated company","Remove the customer data"]','Flag concentration as a diligence and downside risk and test its effect','Professional judgment connects a risk to diligence, downside and the recommendation.','active'),
('ibd9','investment-banking','2.0','cmp_ib_comm',9,'Which email update is most useful to an Associate?','["Done.","The model changed a lot.","Updated the valuation: median comps imply $22.30/share; DCF implies $30.80/share. I flagged the share-count mismatch and attached the revised output.","I worked on the file for two hours."]','Updated the valuation: median comps imply $22.30/share; DCF implies $30.80/share. I flagged the share-count mismatch and attached the revised output.','Useful analyst communication is concise, specific and decision-relevant.','active'),
('ibd10','investment-banking','2.0','cmp_ib_detail',10,'Before sending a client-ready valuation page, what is the best final check?','["Only spell-check the title","Reconcile numbers to the model, check labels/units, sources, dates and formatting consistency","Change every font","Remove sensitivity analysis"]','Reconcile numbers to the model, check labels/units, sources, dates and formatting consistency','Attention to detail requires numerical and presentation-quality checks.','active'),
('ibd11','investment-banking','2.0','cmp_ib_accounting',11,'If depreciation expense increases by $10m with a 25% tax rate, what is the approximate impact on net income, all else equal?','["Down $10m","Down $7.5m","Up $7.5m","No impact"]','Down $7.5m','The after-tax income-statement impact is $10m × (1−25%) = $7.5m lower net income.','active'),
('ibd12','investment-banking','2.0','cmp_ib_ev',12,'When valuing a company with options and restricted stock, why does diluted share count matter?','["It can affect equity value per share","It changes reported revenue","It eliminates debt","It sets WACC automatically"]','It can affect equity value per share','Dilution changes the share count used to translate aggregate equity value into per-share value.','active');

INSERT OR REPLACE INTO role_lab_definitions
(lab_key,version,pathway_id,title,role_title,client_name,scenario_json,pass_score,status) VALUES
('ib-project-northstar','2.0','investment-banking','Project Northstar — M&A Analyst Readiness','Investment Banking Analyst','Apex Systems',
'{"desk":"Industrials M&A","associate":"Maya Chen","vp":"Daniel Brooks","target":"Northstar Components","buyer":"Apex Systems","timeline":"Monday, 8:46 AM","context":"Apex Systems is evaluating an acquisition of Northstar Components. You are the analyst responsible for valuation, transaction analysis, model review and the first draft of the recommendation.","historicals":{"2024":{"revenue":520,"ebitda":72},"2025":{"revenue":570,"ebitda":82},"2026":{"revenue":620,"ebitda":93}},"capitalization":{"share_price":18.5,"diluted_shares":40,"debt":110,"cash":25,"net_debt":85},"management_forecast":{"2027":{"revenue":665,"ebitda_margin":0.155},"2028":{"revenue":715,"ebitda_margin":0.16},"2029":{"revenue":765,"ebitda_margin":0.165}},"comps":[{"name":"Peer A","ev":1200,"ebitda":120},{"name":"Peer B","ev":1650,"ebitda":150},{"name":"Peer C","ev":920,"ebitda":92},{"name":"Peer D","ev":1320,"ebitda":110}],"precedents":[{"name":"Deal Alpha","multiple":9.8},{"name":"Deal Bravo","multiple":11.2},{"name":"Deal Charlie","multiple":10.6}],"dcf":{"fcf":[70,78,85,91,97],"wacc":0.09,"terminal_growth":0.025},"offer":{"price_per_share":26,"debt_funding_pct":0.4},"note":"All companies, people and data in this case are synthetic and created for training."}',80,'active');

INSERT OR REPLACE INTO role_lab_tasks
(id,lab_key,lab_version,stage_no,title,task_type,brief_json,grading_json,competency_map_json,pass_score,max_attempts,required,status) VALUES
('ibnl1','ib-project-northstar','2.0',1,'Build the transaction snapshot','numeric_fields',
'{"timestamp":"9:08 AM","from":"Maya Chen — Associate","message":"Start with a clean transaction snapshot. I need the 2026 margin, current equity value, current enterprise value and net debt before we discuss valuation.","fields":[{"id":"ebitda_margin","label":"2026 EBITDA margin","suffix":"%"},{"id":"equity_value","label":"Current equity value","prefix":"$","suffix":"m"},{"id":"enterprise_value","label":"Current enterprise value","prefix":"$","suffix":"m"},{"id":"net_debt","label":"Net debt","prefix":"$","suffix":"m"}]}',
'{"rules":[{"field":"ebitda_margin","type":"numeric","expected":15,"tolerance":0.15,"points":25,"feedback":"Recheck EBITDA ÷ revenue."},{"field":"equity_value","type":"numeric","expected":740,"tolerance":1,"points":25,"feedback":"Use diluted shares × current share price."},{"field":"enterprise_value","type":"numeric","expected":825,"tolerance":1,"points":25,"feedback":"Bridge equity value to enterprise value using net debt."},{"field":"net_debt","type":"numeric","expected":85,"tolerance":0.5,"points":25,"feedback":"Debt less cash equals net debt."}]}',
'{"cmp_ib_accounting":0.35,"cmp_ib_ev":0.45,"cmp_ib_detail":0.20}',70,3,1,'active'),

('ibnl2','ib-project-northstar','2.0',2,'Trading comparables valuation','numeric_fields',
'{"timestamp":"10:02 AM","from":"Maya Chen — Associate","message":"Run the trading comps. Calculate each EV / EBITDA multiple, the median, and the implied value using Northstar 2026 EBITDA. Show me the implied share price.","fields":[{"id":"peer_a","label":"Peer A EV / EBITDA","suffix":"x"},{"id":"peer_b","label":"Peer B EV / EBITDA","suffix":"x"},{"id":"peer_c","label":"Peer C EV / EBITDA","suffix":"x"},{"id":"peer_d","label":"Peer D EV / EBITDA","suffix":"x"},{"id":"median","label":"Median multiple","suffix":"x"},{"id":"implied_ev","label":"Implied enterprise value","prefix":"$","suffix":"m"},{"id":"implied_share","label":"Implied share price","prefix":"$"}]}',
'{"rules":[{"field":"peer_a","type":"numeric","expected":10,"tolerance":0.05,"points":10,"feedback":"Peer A: EV ÷ EBITDA."},{"field":"peer_b","type":"numeric","expected":11,"tolerance":0.05,"points":10,"feedback":"Peer B: EV ÷ EBITDA."},{"field":"peer_c","type":"numeric","expected":10,"tolerance":0.05,"points":10,"feedback":"Peer C: EV ÷ EBITDA."},{"field":"peer_d","type":"numeric","expected":12,"tolerance":0.05,"points":10,"feedback":"Peer D: EV ÷ EBITDA."},{"field":"median","type":"numeric","expected":10.5,"tolerance":0.05,"points":15,"feedback":"Sort the four multiples and average the two middle observations."},{"field":"implied_ev","type":"numeric","expected":976.5,"tolerance":2,"points":20,"feedback":"Apply the median multiple to Northstar 2026 EBITDA."},{"field":"implied_share","type":"numeric","expected":22.2875,"tolerance":0.08,"points":25,"feedback":"Bridge implied EV to equity value, then divide by diluted shares."}]}',
'{"cmp_ib_comps":0.50,"cmp_ib_ev":0.30,"cmp_ib_detail":0.20}',70,3,1,'active'),

('ibnl3','ib-project-northstar','2.0',3,'DCF cross-check','numeric_fields',
'{"timestamp":"11:14 AM","from":"Daniel Brooks — VP","message":"I want an independent DCF cross-check before lunch. Use the provided five-year FCF forecast, 9.0% WACC and 2.5% terminal growth. Give me PV of forecast FCF, PV of terminal value, enterprise value and implied share price.","fields":[{"id":"pv_fcf","label":"PV of forecast FCF","prefix":"$","suffix":"m"},{"id":"pv_terminal","label":"PV of terminal value","prefix":"$","suffix":"m"},{"id":"dcf_ev","label":"DCF enterprise value","prefix":"$","suffix":"m"},{"id":"dcf_share","label":"DCF implied share price","prefix":"$"}]}',
'{"rules":[{"field":"pv_fcf","type":"numeric","expected":323.0169,"tolerance":2,"points":25,"feedback":"Discount each annual FCF back to present value."},{"field":"pv_terminal","type":"numeric","expected":994.1450,"tolerance":4,"points":25,"feedback":"Calculate terminal value using Gordon Growth, then discount it back five years."},{"field":"dcf_ev","type":"numeric","expected":1317.1619,"tolerance":5,"points":25,"feedback":"Enterprise value is PV of forecast FCF plus PV of terminal value."},{"field":"dcf_share","type":"numeric","expected":30.8040,"tolerance":0.15,"points":25,"feedback":"Bridge DCF enterprise value to equity value, then divide by diluted shares."}]}',
'{"cmp_ib_dcf":0.60,"cmp_ib_ev":0.20,"cmp_ib_detail":0.20}',70,3,1,'active'),

('ibnl4','ib-project-northstar','2.0',4,'Analyze the proposed acquisition','mixed',
'{"timestamp":"12:36 PM","from":"Maya Chen — Associate","message":"Apex is considering $26.00 per share. Calculate purchase equity value, purchase enterprise value and premium to Northstar current share price. Then tell me which valuation cross-check the offer exceeds.","fields":[{"id":"purchase_equity","label":"Purchase equity value","type":"number","prefix":"$","suffix":"m"},{"id":"purchase_ev","label":"Purchase enterprise value","type":"number","prefix":"$","suffix":"m"},{"id":"premium","label":"Premium to current share price","type":"number","suffix":"%"},{"id":"exceeds","label":"At $26/share, which current cross-check is exceeded?","type":"choice","options":["Trading comps only","DCF only","Both trading comps and DCF","Neither"]}]}',
'{"rules":[{"field":"purchase_equity","type":"numeric","expected":1040,"tolerance":2,"points":25,"feedback":"Offer price × diluted shares."},{"field":"purchase_ev","type":"numeric","expected":1125,"tolerance":2,"points":25,"feedback":"Purchase equity value + net debt."},{"field":"premium","type":"numeric","expected":40.5405,"tolerance":0.3,"points":25,"feedback":"Compare $26.00 with the current $18.50 share price."},{"field":"exceeds","type":"choice","expected":"Trading comps only","points":25,"feedback":"Compare the offer with the trading-comps and DCF implied share prices."}]}',
'{"cmp_ib_ma":0.45,"cmp_ib_judgment":0.25,"cmp_ib_ev":0.20,"cmp_ib_detail":0.10}',70,3,1,'active'),

('ibnl5','ib-project-northstar','2.0',5,'Model review — find the problems','multi_select',
'{"timestamp":"1:11 PM","from":"Maya Chen — Associate","message":"I reviewed the draft model and something is off. Before I mark it up, do a full QA pass. Select every issue that would materially distort the valuation or transaction analysis.","field":{"id":"issues","options":["The model uses 38 basic shares instead of 40 diluted shares","Cash is added instead of subtracted in the enterprise-value bridge","The comps page applies the median multiple to 2025 EBITDA instead of 2026 EBITDA","The DCF terminal-growth assumption is 4.0% even though the case instruction says 2.5%","The company name is centered on the cover page","Peer B has a different fiscal year-end month","The workbook uses blue font for hardcodes","The target logo is on the top right"]}}',
'{"rules":[{"field":"issues","type":"multi_select","expected":["The model uses 38 basic shares instead of 40 diluted shares","Cash is added instead of subtracted in the enterprise-value bridge","The comps page applies the median multiple to 2025 EBITDA instead of 2026 EBITDA","The DCF terminal-growth assumption is 4.0% even though the case instruction says 2.5%"],"points":100,"feedback":"Focus on issues that change dilution, enterprise value, valuation inputs or DCF assumptions. Selecting harmless presentation conventions reduces the QA score."}]}',
'{"cmp_ib_review":0.65,"cmp_ib_detail":0.35}',75,3,1,'active'),

('ibnl6','ib-project-northstar','2.0',6,'Management changes the outlook','mixed',
'{"timestamp":"1:37 PM","from":"Maya Chen — Associate","message":"New information: management cut 2028 revenue from $715m to $680m and EBITDA margin from 16.0% to 14.5%. Update the 2028 EBITDA and tell me the first-order valuation implication.","fields":[{"id":"revised_ebitda","label":"Revised 2028 EBITDA","type":"number","prefix":"$","suffix":"m"},{"id":"direction","label":"First-order valuation implication","type":"choice","options":["Valuation pressure downward","Valuation automatically increases","No possible valuation effect","Only diluted shares change"]}]}',
'{"rules":[{"field":"revised_ebitda","type":"numeric","expected":98.6,"tolerance":0.3,"points":60,"feedback":"Revised revenue × revised EBITDA margin."},{"field":"direction","type":"choice","expected":"Valuation pressure downward","points":40,"feedback":"Lower operating performance generally pressures value, all else equal."}]}',
'{"cmp_ib_accounting":0.20,"cmp_ib_dcf":0.25,"cmp_ib_judgment":0.35,"cmp_ib_detail":0.20}',70,3,1,'active'),

('ibnl7','ib-project-northstar','2.0',7,'Send the Associate your recommendation','written_decision',
'{"timestamp":"3:12 PM","from":"Maya Chen — Associate","message":"Send me your recommendation before the VP check-in. I need a clear stance, valuation evidence, the effect of management’s revised outlook, and the biggest diligence or execution risk. Keep it concise.","fields":[{"id":"stance","label":"Recommendation","type":"choice","options":["Proceed at $26 with no further work","Proceed, but seek price protection / renegotiate","Pause pending diligence","Walk away immediately"]},{"id":"memo","label":"Associate update","type":"textarea","maxLength":2200}]}',
'{"rules":[{"field":"stance","type":"choice_flexible","preferred":["Proceed, but seek price protection / renegotiate","Pause pending diligence"],"points":25,"feedback":"A defensible stance should reflect the mixed valuation evidence and the downward revision."},{"field":"memo","type":"text_evidence","points":75,"min_chars":180,"evidence_groups":[["26","offer"],["22.3","22.29","trading comps","comps"],["30.8","30.80","dcf"],["98.6","revised","680","14.5"],["risk","diligence","downside","customer","execution"]],"feedback":"Your update should state a recommendation and connect it to valuation, the revised outlook and a concrete risk/diligence point."}]}',
'{"cmp_ib_judgment":0.40,"cmp_ib_comm":0.35,"cmp_ib_detail":0.10,"cmp_ib_ma":0.15}',70,3,1,'active');
