PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO credential_definitions (id,pathway_id,credential_level,standard_version,title,track,learner_level,description,requirements_json,sort_order,status) VALUES ('academy-finance-core','finance-core','finance_core','2.0-academy','Capital Mastery Finance Core Certificate','foundations','intermediate','Cross-functional finance breadth credential requiring Foundations mastery across at least four careers spanning at least three finance domains.','{"foundations_credentials":4,"minimum_domains":3}',10,'active');
INSERT OR REPLACE INTO credential_definitions (id,pathway_id,credential_level,standard_version,title,track,learner_level,description,requirements_json,sort_order,status) VALUES ('academy-deals','academy-deals','academy','2.0-academy','Capital Mastery Deals Academy Certificate','professional','advanced','Cross-role Deals credential requiring Professional Readiness in both Investment Banking and Corporate Development.','{"required_pathways":["investment-banking","corporate-development"]}',20,'active');
INSERT OR REPLACE INTO credential_definitions (id,pathway_id,credential_level,standard_version,title,track,learner_level,description,requirements_json,sort_order,status) VALUES ('academy-investing','academy-investing','academy','2.0-academy','Capital Mastery Investing Academy Certificate','professional','advanced','Cross-role investing credential requiring Professional Readiness in at least two investing/research pathways.','{"minimum_professional_readiness":2,"eligible_pathways":["private-equity","venture-capital","equity-research","asset-management","hedge-funds"]}',30,'active');
INSERT OR REPLACE INTO credential_definitions (id,pathway_id,credential_level,standard_version,title,track,learner_level,description,requirements_json,sort_order,status) VALUES ('academy-markets-quant','academy-markets-quant','academy','2.0-academy','Capital Mastery Markets & Quant Academy Certificate','professional','advanced','Markets/quant credential requiring Professional Readiness in at least two of Sales & Trading, Quantitative Finance and Risk Management.','{"minimum_professional_readiness":2,"eligible_pathways":["sales-trading","quantitative-finance","risk-management"]}',40,'active');
INSERT OR REPLACE INTO credential_definitions (id,pathway_id,credential_level,standard_version,title,track,learner_level,description,requirements_json,sort_order,status) VALUES ('academy-credit-risk','academy-credit-risk','academy','2.0-academy','Capital Mastery Credit & Risk Academy Certificate','professional','advanced','Credit/risk credential requiring Professional Readiness in at least two of Private Credit, Corporate Banking and Risk Management.','{"minimum_professional_readiness":2,"eligible_pathways":["private-credit","corporate-banking","risk-management"]}',50,'active');
INSERT OR REPLACE INTO credential_definitions (id,pathway_id,credential_level,standard_version,title,track,learner_level,description,requirements_json,sort_order,status) VALUES ('academy-corporate-finance','academy-corporate-finance','academy','2.0-academy','Capital Mastery Corporate Finance Academy Certificate','professional','advanced','Corporate-finance credential requiring Professional Readiness in at least two of FP&A, Treasury and Corporate Development.','{"minimum_professional_readiness":2,"eligible_pathways":["fp-and-a","treasury","corporate-development"]}',60,'active');
INSERT OR REPLACE INTO credential_definitions (id,pathway_id,credential_level,standard_version,title,track,learner_level,description,requirements_json,sort_order,status) VALUES ('academy-wealth-real-assets','academy-wealth-real-assets','academy','2.0-academy','Capital Mastery Wealth & Real Assets Academy Certificate','professional','advanced','Client/real-assets credential requiring Professional Readiness in both Wealth Management and Real Estate Finance.','{"required_pathways":["wealth-management","real-estate-finance"]}',70,'active');
INSERT OR REPLACE INTO credential_definitions (id,pathway_id,credential_level,standard_version,title,track,learner_level,description,requirements_json,sort_order,status) VALUES ('academy-finance-professional','finance-professional','finance_professional','2.0-academy','Capital Mastery Finance Professional Achievement','professional','advanced','Highest cross-career Capital Mastery achievement requiring Finance Core plus Professional Readiness in at least four careers spanning at least three Academy domains.','{"requires_finance_core":true,"professional_readiness_credentials":4,"minimum_domains":3}',100,'active');
